version: '2'
services:
    flowers-app:
        image: flowers
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://flowers-mysql:3306/flowers?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    flowers-mysql:
        extends:
            file: mysql.yml
            service: flowers-mysql
