import {CUSTOM_ELEMENTS_SCHEMA, NgModule} from '@angular/core';
import {RouterModule} from '@angular/router';
import {FlowersSharedModule} from '../shared';
import {FlowersAdminModule} from '../admin/admin.module';
import {
    companyConfigurationState,
    BlockComponent,
    BlockDeleteDialogComponent,
    BlockDeletePopupComponent,
    BlockDetailComponent,
    BlockDialogComponent,
    BlockPopupComponent,
    BlockPopupService,
    BlockResolvePagingParams,
    BlockService,
    SortComponent,
    SortDeleteDialogComponent,
    SortDeletePopupComponent,
    SortDetailComponent,
    SortDialogComponent,
    SortPopupComponent,
    SortPopupService,
    SortResolvePagingParams,
    SortService,
    DiseaseService,
    DiseasePopupService,
    DiseaseComponent,
    DiseaseDetailComponent,
    DiseaseDialogComponent,
    DiseasePopupComponent,
    DiseaseDeletePopupComponent,
    DiseaseDeleteDialogComponent,
    DiseaseResolvePagingParams,
    EmployeeComponent,
    EmployeeDeleteDialogComponent,
    EmployeeDeletePopupComponent,
    EmployeeDetailComponent,
    EmployeeDialogComponent,
    EmployeePopupComponent,
    EmployeePopupService,
    EmployeeResolvePagingParams,
    EmployeeService
} from './';

@NgModule({
    imports: [
        FlowersSharedModule,
        FlowersAdminModule,
        RouterModule.forRoot(companyConfigurationState, { useHash: true })
    ],
    declarations: [
        BlockComponent,
        BlockDetailComponent,
        BlockDialogComponent,
        BlockDeleteDialogComponent,
        BlockPopupComponent,
        BlockDeletePopupComponent,
        SortComponent,
        SortDetailComponent,
        SortDialogComponent,
        SortDeleteDialogComponent,
        SortPopupComponent,
        SortDeletePopupComponent,
        DiseaseComponent,
        DiseaseDetailComponent,
        DiseaseDialogComponent,
        DiseaseDeleteDialogComponent,
        DiseasePopupComponent,
        DiseaseDeletePopupComponent,
        EmployeeComponent,
        EmployeeDetailComponent,
        EmployeeDialogComponent,
        EmployeeDeleteDialogComponent,
        EmployeePopupComponent,
        EmployeeDeletePopupComponent,
    ],
    entryComponents: [
        BlockComponent,
        BlockDialogComponent,
        BlockPopupComponent,
        BlockDeleteDialogComponent,
        BlockDeletePopupComponent,
        SortComponent,
        SortDialogComponent,
        SortPopupComponent,
        SortDeleteDialogComponent,
        SortDeletePopupComponent,
        DiseaseComponent,
        DiseaseDialogComponent,
        DiseasePopupComponent,
        DiseaseDeleteDialogComponent,
        DiseaseDeletePopupComponent,
        EmployeeComponent,
        EmployeeDialogComponent,
        EmployeePopupComponent,
        EmployeeDeleteDialogComponent,
        EmployeeDeletePopupComponent,
    ],
    providers: [
        BlockService,
        BlockPopupService,
        BlockResolvePagingParams,
        SortService,
        SortPopupService,
        SortResolvePagingParams,
        DiseaseService,
        DiseasePopupService,
        DiseaseResolvePagingParams,
        EmployeeService,
        EmployeePopupService,
        EmployeeResolvePagingParams,
    ],
    schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class FlowersCompanyConfigurationModule {}
